/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Wed Nov  7 11:50:31 2018. */

#include "message.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t nbiot_e2e_Message_fields[2] = {
    PB_ONEOF_FIELD(message,   1, MESSAGE , ONEOF, STATIC  , FIRST, nbiot_e2e_Message, ping_message, ping_message, &nbiot_e2e_PingMessage_fields),
    PB_LAST_FIELD
};

const pb_field_t nbiot_e2e_PingMessage_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, nbiot_e2e_PingMessage, sequence, sequence, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, nbiot_e2e_PingMessage, prev_rssi, sequence, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, nbiot_e2e_PingMessage, nbiot_lib_hash, prev_rssi, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, nbiot_e2e_PingMessage, e2e_hash, nbiot_lib_hash, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(nbiot_e2e_Message, message.ping_message) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_nbiot_e2e_Message_nbiot_e2e_PingMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(nbiot_e2e_Message, message.ping_message) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_nbiot_e2e_Message_nbiot_e2e_PingMessage)
#endif


/* @@protoc_insertion_point(eof) */
